APP_NAME=marketdata
APP_HOME=/Users/vikasbhandekar/live_services/marketdata

BINARY_PATH=${APP_HOME}/cmd/marketdata
CONFIG_PATH=${APP_HOME}/config/marketdata_go_feed_config.json
LOG_PATH=${APP_HOME}/logs
PID_FILE=${APP_HOME}/marketdata.pid
SERVICE_FILE=~/Library/LaunchAgents/com.marketdata.service.plist
