APP_NAME=python_feed
APP_HOME=/usr/local/python_feed

BINARY_PATH=${APP_HOME}/main/main.py
CONFIG_PATH=${APP_HOME}/config/ws_feed_config.json
LOG_PATH=${APP_HOME}/logs/service.log
PID_FILE=${APP_HOME}/python_feed.pid
SERVICE_FILE=~/Library/LaunchAgents/com.python_feed.service.plist
