APP_NAME=paper_engine
APP_HOME=/Users/vikasbhandekar/live_services/paper_engine

BINARY_PATH=${APP_HOME}/cmd/paper_engine
CONFIG_PATH=${APP_HOME}/config/paper_engine_config.json
LOG_PATH=${APP_HOME}/logs/paper_engine.log
PID_FILE=${APP_HOME}/paper_engine.pid
SERVICE_FILE=/etc/systemd/system/paper_engine.service
