APP_NAME=first_candle_strategy
APP_HOME=/Users/vikasbhandekar/live_services/first_candle_strategy

BINARY_PATH=${APP_HOME}/cmd/first_candle_strategy
CONFIG_PATH=${APP_HOME}/config/first_candle_strategy_config.json
LOG_PATH=${APP_HOME}/logs/first_candle_strategy.log
PID_FILE=${APP_HOME}/first_candle_strategy.pid
SERVICE_FILE=~/Library/LaunchAgents/com.first_candle_strategy.service.plist
