package strategy

import "time"

// Candle represents a 1-minute OHLCV bar with VWAP consumed from Kafka.
// It is used both for index bias and stock strategy processing.
type Candle struct {
	Symbol    string    `json:"symbol"`
	Time      time.Time `json:"time"`
	Timeframe string    `json:"timeframe"`
	Open      float64   `json:"open"`
	High      float64   `json:"high"`
	Low       float64   `json:"low"`
	Close     float64   `json:"close"`
	Volume    int64     `json:"volume"`
	VWAP      float64   `json:"vwap"`
}

// MarketBias represents the overall market direction derived from index behavior.
type MarketBias string

const (
	BiasNone  MarketBias = "NONE"
	BiasLong  MarketBias = "LONG_ONLY"
	BiasShort MarketBias = "SHORT_ONLY"
)

// SignalSide describes the direction of a signal.
type SignalSide string

const (
	SideBuy  SignalSide = "BUY"
	SideSell SignalSide = "SELL" // reserved for future
)

// StrategySignal represents a trading signal generated by the VWAP strategy.
// It omits quantities or broker-specific details; downstream services handle execution.
type StrategySignal struct {
	Strategy string     `json:"strategy"`
	Symbol   string     `json:"symbol"`
	Side     SignalSide `json:"side"`
	Time     time.Time  `json:"time"`
	Reason   string     `json:"reason"`
}
