APP_NAME=ldrb_strategy
APP_HOME=/Users/vikasbhandekar/live_services/ldrb_strategy

BINARY_PATH=${APP_HOME}/cmd/ldrb_strategy
CONFIG_PATH=${APP_HOME}/config/ldrb_strategy_config.json
LOG_PATH=${APP_HOME}/logs/ldrb_strategy.log
PID_FILE=${APP_HOME}/ldrb_strategy.pid
SERVICE_FILE=~/Library/LaunchAgents/com.ldrb_strategy.service.plist

