APP_NAME=vwap_strategy
APP_HOME=/Users/vikasbhandekar/live_services/vwap_strategy

BINARY_PATH=${APP_HOME}/cmd/vwap_strategy
CONFIG_PATH=${APP_HOME}/config/vwap_strategy_config.json
LOG_PATH=${APP_HOME}/logs/vwap_strategy.log
PID_FILE=${APP_HOME}/vwap_strategy.pid
SERVICE_FILE=~/Library/LaunchAgents/com.vwap_strategy.service.plist
